language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
before_script:
  - composer install --prefer-dist --dev
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/coverage/clover.xml
